version: "3"
services:
  # node-test:
  #   build:
  #     context: .
  #   image: node-test
  #   container_name: node-test
  #   ports:
  #     - "8080:8080"
  jenkins-docker:
    container_name: jenkins-docker
    privileged: true
    network_mode: jenkins
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - "jenkins-docker-certs:/certs/client"
      - "jenkins-data:/var/jenkins_home"
    ports:
      - "2376:2376"
    image: "docker:dind"
  jenkins-blueocean:
    container_name: jenkins-blueocean
    network_mode: jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - "jenkins-data:/var/jenkins_home"
      - "jenkins-docker-certs:/certs/client:ro"
    ports:
      - "8080:8080"
      - "50000:50000"
    image: jenkinsci/blueocean
    
volumes:
  jenkins-data:
  jenkins-docker-certs:

